FROM docker.io/library/ubuntu:24.04
LABEL org.opencontainers.image.base.name="docker.io/library/ubuntu:24.04"

### Global ARG declarations ###
ARG DEBIAN_FRONTEND=noninteractive
ARG BUILDARCH
ARG TARGETARCH=${BUILDARCH}

### Release ARG declarations ###
ARG BUILDARCH
ARG TARGETARCH=${BUILDARCH}
ARG RSTUDIO_INSTALL_NO_LICENSE_INITIALIZATION=1

### ENV declarations ###
ENV PCT_LICENSE=""
ENV PCT_LICENSE_SERVER=""
ENV PCT_LICENSE_FILE_PATH=""
ENV PCT_STARTUP_DEBUG=0

SHELL ["/bin/bash", "-euo", "pipefail", "-c"]

### Run setup ###
RUN echo 'Acquire::Retries "3"; Acquire::http::Timeout "30"; Acquire::https::Timeout "30";' > /etc/apt/apt.conf.d/99-retries && \
    apt-get update -yqq --fix-missing && \
    apt-get upgrade -yqq && \
    apt-get dist-upgrade -yqq && \
    apt-get autoremove -yqq --purge && \
    apt-get install -yqq --no-install-recommends \
        curl \
        ca-certificates \
        gnupg \
        tar && \
    apt-get install -yqq --no-install-recommends locales && \
    localedef -i en_US -f UTF-8 en_US.UTF-8 && \
    bash -c "$(curl -1fsSL 'https://dl.posit.co/public/pro/setup.deb.sh')" && \
    apt-get clean -yqq && \
    rm -rf /var/lib/apt/lists/*
ENV LANG=en_US.UTF-8
ENV LANGUAGE=en_US:en
ENV LC_ALL=en_US.UTF-8

### Update apt packages ###
COPY connect/2026.07/deps/ubuntu-24.04_packages.txt /tmp/ubuntu-24.04_packages.txt
RUN apt-get update -yqq && \
    xargs -a /tmp/ubuntu-24.04_packages.txt apt-get install -yqq --no-install-recommends && \
    apt-get clean -yqq && \
    rm -rf /var/lib/apt/lists/*

### Install Connect ###
ARG CONNECT_VERSION="2026.07.0"
COPY connect/2026.07/conf/rstudio-connect.gcfg /tmp/rstudio-connect.gcfg
COPY --chmod=0775 connect/2026.07/scripts/install_connect.sh /tmp/install_connect.sh
RUN IMAGE_VARIANT="Minimal" \
        /tmp/install_connect.sh && \
    sed -i 's/<CRAN_URL>/https:\/\/p3m.dev\/cran\/__linux__\/noble\/latest/g' /etc/rstudio-connect/rstudio-connect.gcfg && \
    rm -f /tmp/install_connect.sh /tmp/rstudio-connect.gcfg

### Copy scripts ###
COPY --chmod=0775 connect/2026.07/scripts/startup.sh /usr/local/bin/startup.sh

### Create data volume ###
VOLUME ["/data"]

### Finalize image ###
EXPOSE 3939/tcp
HEALTHCHECK --interval=30s --timeout=5s --start-period=60s --retries=3 \
    CMD curl --fail --silent --output /dev/null http://localhost:3939/__ping__
CMD ["/usr/local/bin/startup.sh"]
