FROM docker.io/library/ubuntu:22.04
LABEL org.opencontainers.image.base.name="docker.io/library/ubuntu:22.04"

### Global ARG declarations ###
ARG DEBIAN_FRONTEND=noninteractive
ARG PTI_VERSION="0.0.4"
ARG PTI_NO_COLOR="true"
ARG PTI_LOG_FORMAT="json"

### Release ARG declarations ###
{% if not image_type == "min" %}
ARG R_VERSION="{{ r_version }}"
ARG PYTHON_VERSION="{{ python_version }}"
ARG QUARTO_VERSION="{{ quarto_version }}"
{%- endif %}
ARG CONNECT_VERSION="{{ image_version }}"
ARG RSTUDIO_INSTALL_NO_LICENSE_INITIALIZATION=1

### ENV declarations ###
ENV PCT_LICENSE=""
ENV PCT_LICENSE_SERVER=""
ENV PCT_LICENSE_FILE_PATH=""
ENV STARTUP_DEBUG_MODE=0

### Install Posit Tool Installer ###
# TODO: Uncomment when PTI is available as a public repository
#ADD --chmod=0755 \
#    https://github.com/posit-dev/pti/releases/download/v${PTI_VERSION}/pti_${PTI_VERSION}_linux_amd64 \
#    /usr/local/bin/pti
# FIXME(ianpittwood): This is a shim to get around Github private repo authentication. ADD is a better solution once
#                     pti is available publicly.
COPY --chmod=0755 ./tools/pti /usr/local/bin/pti

### Initialize PTI in container ###
RUN pti init

### Update apt packages ###
COPY {{ rel_path }}/deps/ubuntu2204_packages.txt /tmp/ubuntu2204_packages.txt
RUN pti syspkg update \
    && pti syspkg upgrade --dist \
    && pti syspkg install -f /tmp/ubuntu2204_packages.txt \
    && rm -f /tmp/ubuntu2204_packages.txt

{% if not image_type == "min" %}
### Install Pro Drivers ###
RUN pti pro-drivers install --copy-odbcinst

### Install R ###
RUN pti r install --add-to-path --default "${R_VERSION}"

### Install Python and Jupyter ###
RUN pti python install --add-to-path --default "${PYTHON_VERSION}"

### Install Quarto and TinyTex ###
RUN pti quarto install --add-to-path "${QUARTO_VERSION}" \
    && pti quarto tinytex install --add-to-path

### Install TensorFlow Serving ###
COPY --chmod=0775 ./{{ rel_path }}/scripts/install_tensorflow.sh /tmp/install_tensorflow.sh
RUN /tmp/install_tensorflow.sh \
    && rm -f /tmp/install_tensorflow.sh
{% endif %}

COPY --chmod=0775 ./{{ rel_path }}/scripts/install_connect.sh /tmp/install_connect.sh
RUN OS_URL=ubuntu22 /tmp/install_connect.sh \
    && rm -f /tmp/install_connect.sh

### Configure application/image ###
COPY ./{{ rel_path }}/conf/rstudio-connect.gcfg /etc/rstudio-connect/rstudio-connect.gcfg
VOLUME ["/data"]

### Copy scripts ###
COPY --chmod=0775 ./{{ rel_path }}/scripts/startup.sh /usr/local/bin/startup.sh

### Finalize image ###
{% if not image_type == "min" -%}
LABEL co.posit.image.tools.python="{{ python_version }}" \
      co.posit.image.tools.r="{{ r_version }}" \
      co.posit.image.tools.quarto="{{ quarto_version }}"
{% endif %}
EXPOSE 3939/tcp
CMD ["/usr/local/bin/startup.sh"]
