FROM docker.io/library/ubuntu:22.04
LABEL org.opencontainers.image.base.name="docker.io/library/ubuntu:22.04"

### ARG declarations ###
ARG DEBIAN_FRONTEND=noninteractive
ARG PTI_VERSION="0.0.1"
ARG PTI_NO_COLOR="true"
ARG PTI_LOG_FORMAT="json"
{%- if not image_type == "min" %}
ARG PYTHON_VERSION="{{ python_version }}"
ARG R_VERSION="{{ r_version }}"
ARG QUARTO_VERSION="{{ quarto_version }}"
{%- endif %}
ARG CONNECT_VERSION="{{ image_version }}"

### ENV declarations ###
ENV PCT_LICENSE ""
ENV PCT_LICENSE_SERVER ""
ENV PCT_LICENSE_FILE_PATH ""
ENV STARTUP_DEBUG_MODE 0

### Install Posit Tool Installer ###
# TODO: Uncomment when PTI is available as a public repository
#ADD --chmod=0755 \
#    https://github.com/posit-dev/pti/releases/download/v${PTI_VERSION}/pti_${PTI_VERSION}_linux_amd64 \
#    /usr/local/bin/pti
# FIXME(ianpittwood): This is a shim to get around Github private repo authentication. ADD is a better solution once
#                     pti is available publicly.
COPY --chmod=0755 ./tools/pti /usr/local/bin/pti

### Initialize PTI in container ###
RUN pti init

### Install Apt packages ###
COPY ./{{ rel_path }}/deps/ubuntu2204_packages.txt /tmp/packages.txt
RUN pti syspkg update \
    && pti syspkg upgrade --dist \
    && pti syspkg install -f /tmp/packages.txt \
    && pti syspkg clean

### Install tini ###
RUN pti tini install

{% if not image_type == "min" -%}
### Install Quarto and TinyTex ###
RUN pti quarto install -V ${QUARTO_VERSION} --add-to-path \
    && pti quarto tinytex install --add-to-path

### Install R ###
RUN pti r install -V ${R_VERSION} --add-to-path --default

### Install Python and Jupyter ###
RUN pti python install -V ${PYTHON_VERSION} --add-to-path --default

### Install Pro Drivers ###
RUN pti pro-drivers install --copy-odbcinst

### Install TensorFlow Serving ###
COPY --chmod=0775 ./{{ rel_path }}/scripts/install_tensorflow.sh /tmp/install_tensorflow.sh
RUN /tmp/install_tensorflow.sh \
    && rm -f /tmp/install_tensorflow.sh
{% endif %}
### Install Connect {{ image_version }} ###
COPY --chmod=0775 ./{{ rel_path }}/scripts/install_connect.sh /tmp/install_connect.sh
RUN OS_URL=ubuntu22 /tmp/install_connect.sh \
    && rm -f /tmp/install_connect.sh

### Configure application/image ###
COPY ./{{ rel_path }}/conf/rstudio-connect.gcfg /etc/rstudio-connect/rstudio-connect.gcfg
VOLUME ["/data"]

### Copy scripts ###
COPY --chmod=0775 ./{{ rel_path }}/scripts/startup.sh /usr/local/bin/startup.sh

### Finalize image ###
{%- if not image_type == "min" %}
LABEL co.posit.image.tools.python="{{ python_version }}" \
      co.posit.image.tools.r="{{ r_version }}" \
      co.posit.image.tools.quarto="{{ quarto_version }}"
{% endif %}
EXPOSE 3939
ENTRYPOINT ["/usr/local/bin/tini", "--"]
CMD ["/usr/local/bin/startup.sh"]
