{#-
Below are imports for Bakery's macros. If any are unneeded, they can be removed.
Bakery handles bootstrapping the files into template rendering.
-#}
{%- import "apt.j2" as apt -%}
{%- import "python.j2" as python -%}
{%- import "quarto.j2" as quarto -%}
{%- import "r.j2" as r -%}
FROM docker.io/library/ubuntu:22.04
LABEL org.opencontainers.image.base.name="docker.io/library/ubuntu:22.04"

### Global ARG declarations ###
ARG DEBIAN_FRONTEND=noninteractive

### Release ARG declarations ###
ARG CONNECT_VERSION="{{ Image.Version }}"

### Setup environment ###
RUN {{ apt.update_upgrade(clean=False) }} && \
    {{ apt.install(packages=["ca-certificates", "curl"], update=False, clean=True) }}

COPY --chmod=0755 {{ Path.Version }}/scripts/download_runtime.sh /tmp/download_runtime.sh
RUN /tmp/download_runtime.sh && \
    rm -f /tmp/download_runtime.sh

COPY --chmod=0755 {{ Path.Version }}/scripts/entrypoint.sh /usr/local/bin/entrypoint.sh
CMD ["/usr/local/bin/entrypoint.sh"]
